# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ha_vector/messaging/extensions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$ha_vector/messaging/extensions.proto\x12\x1e\x41nki.Vector.external_interface\x1a google/protobuf/descriptor.proto:3\n\x08streamed\x12\x1f.google.protobuf.MessageOptions\x18\xe0\xd4\x03 \x01(\x08\x62\x06proto3')


STREAMED_FIELD_NUMBER = 60000
streamed = DESCRIPTOR.extensions_by_name['streamed']

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(streamed)

  DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
