default_config:

logger:
  default: warning
  logs:
    custom_components.vector: debug
    ha_vector: debug
# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
