#!/usr/bin/env bash

set -e

mkdir ~/.codex
cp /etc/codex/auth.json ~/.codex/auth.json

sudo curl -L https://github.com/AlexxIT/go2rtc/releases/download/v1.9.13/go2rtc_linux_amd64 --output /bin/go2rtc
sudo chmod a+x /bin/go2rtc
pip3 install uv==0.6.8

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt
python3 -m pip install ffmpeg

sudo apt update
sudo apt install tcpdump libpcap0.8-dev ffmpeg libturbojpeg0 -y